/* UI strings as [vi, en] pairs. Vietnamese is the default; a profile can add or override keys (profile.i18n). */
const STR = {
  "toast.noDetail": ["Mục này chưa có bản chỉnh cho bạn nên chưa có trang chi tiết.", "This entry has no adaptation for you yet, so it has no detail page."],
  "id.profileOf": ["Hồ sơ của {name}", "{name}'s profile"],
  "id.faceLabel": ["Khuôn mặt mộc của bạn", "Your bare face"],
  "prof.name": ["Tên", "Name"],
  "today.faceLabel": ["Gợi ý chỉnh cho bạn", "Suggestion adjusted for you"],
  "today.sug": ["Gợi ý hôm nay", "Today's pick"],
  "today.sugTitle": ["{name}, chỉnh cho {season}", "{name}, adjusted for {season}"],
  "tag.own": ["Đang có", "You own"],
  "today.how": ["Xem cách làm", "See the steps"],
  "today.other": ["Gợi ý khác", "Another pick"],
  "today.skin": ["Chu trình dưỡng da", "Skincare routine"],
  "today.routine": ["Mở routine", "Open routine"],
  "today.shortcuts": ["Lối tắt", "Shortcuts"],
  "sc.check": ["Kiểm tra màu", "Check a colour"],
  "sc.checkSub": ["Trước khi mua", "Before you buy"],
  "sc.lip": ["Bảng màu son", "Lip palette"],
  "sc.lipSub": ["3 màu hợp nhất", "Your 3 best colours"],
  "sc.lib": ["Thư viện layout", "Layout library"],
  "sc.libSub": ["{n} mục", "{n} entries"],
  "sc.buySub": ["{n} món cần mua", "{n} items to buy"],
  "pal.own": ["Đang có", "You own"],
  "pal.finish": ["Chất & finish", "Formula and texture"],
  "pal.summer": ["Hè nóng ẩm.", "Hot, humid summer."],
  "pal.winter": ["Đông hanh khô.", "Dry winter."],
  "pal.onSkin": ["Trên da bạn:", "On your skin:"],
  "pal.peach": ["đào lên hồng", "peach turns pink"],
  "pal.orange": ["cam lên đỏ cam", "orange turns red-orange"],
  "pal.cats": ["Loại sản phẩm", "Product type"],
  "pal.occ": ["Dịp", "Occasion"],
  "pal.allOcc": ["Mọi dịp", "Any occasion"],
  "pal.best": ["Hợp nhất", "Best"],
  "pal.good": ["Hợp", "Also good"],
  "pal.avoid": ["Nên tránh", "Avoid"],
  "pal.howto": ["Cách dùng", "How to use"],
  "lib.popVn": ["Có nguồn VN", "VN source"],
  "lib.all": ["Tất cả", "All"],
  "lib.count": ["{n} mục cộng đồng hay nhắc", "{n} entries the community talks about"],
  "lib.lede": ["Mức hợp tính theo da, bảng màu {season} và khuôn mặt trong hồ sơ. “Hợp với bạn” là mức hợp của layout với bạn, không phải tên layout; dòng chấm cuối thẻ cho biết đồ đang có đã đủ chưa.", "Fit is worked out from the skin, {season} palette and face in your profile. “Fit” rates how well the layout suits you; it is not the layout name. The dot line says whether your kit covers it."],
  "lib.search": ["Tìm: douyin, mắt cún, 청순…", "Search: douyin, puppy eyes, 청순…"],
  "lib.kind": ["Loại", "Type"],
  "lib.filters": ["Bộ lọc", "Filters"],
  "lib.fit": ["Hợp với bạn", "Fit"],
  "lib.region": ["Vùng", "Region"],
  "lib.empty": ["Không có mục nào khớp. Bỏ bớt bộ lọc thử xem.", "Nothing matches. Try removing a filter."],
  "lib.showing": ["Đang hiện {n} / {m} mục", "Showing {n} of {m} entries"],
  "det.stepDone": ["Xong bước {n}", "Step {n} done"],
  "cd.ref": ["Đây là layout tham khảo (truyền thống, sân khấu hoặc nghi lễ), không chỉnh màu cho bạn.", "This is a reference layout (traditional, stage or ritual); it is not adapted to your colouring."],
  "cd.noMine": ["Chưa có bản chỉnh cho bạn. Mức hợp ở trên là gợi ý.", "No adaptation for you yet. The fit above is a hint."],
  "cd.aka": ["Tên gọi khác", "Also called"],
  "cd.bare": ["Khuôn mặt mộc", "Bare face"],
  "cd.bareSub": ["Mục này chưa có màu để vẽ lên mặt bạn", "This entry has no colours to draw on your face yet"],
  "cd.bareRef": ["Layout tham khảo, không vẽ lên mặt bạn", "Reference layout, not drawn on your face"],
  "cd.noSample": ["Chưa lấy mẫu màu", "Colour not sampled"],
  "cd.tech": ["Kỹ thuật chính", "Key techniques"],
  "cd.period": ["Thời kỳ", "Period"],
  "cd.origin": ["Xuất xứ", "Origin"],
  "cd.srcRead": ["Nguồn đã đọc", "Sources read"],
  "cd.srcOther": ["Nguồn tham khảo, chưa đọc", "Other sources, not read"],
  "cd.srcNone": ["Chưa có trang nào được đọc và xác minh.", "No page has been read and verified yet."],
  "cd.srcN": ["{n} nguồn", "{n} sources"],
  "cd.srcZero": ["Chưa xác minh", "Unverified"],
  "cd.low": ["Độ tin cậy thấp: {why}. Xem như gợi ý, chưa phải kết luận.", "Low confidence: {why}. Treat it as a lead, not a conclusion."],
  "cd.low0": ["chưa có trang nào được đọc và xác minh", "no page has been read and verified"],
  "cd.low1": ["chỉ có 1 nguồn", "only one source"],
  "cd.lowThin": ["mô tả còn ít chi tiết", "few details on record"],
  "cd.f.skin": ["Nền", "Base"],
  "cd.f.brows": ["Mày", "Brows"],
  "cd.f.eyes": ["Mắt", "Eyes"],
  "cd.f.liner": ["Kẻ mắt", "Liner"],
  "cd.f.lashes": ["Mi", "Lashes"],
  "cd.f.blush": ["Má", "Blush"],
  "cd.f.contour_bronzer": ["Tạo khối, bronzer", "Contour, bronzer"],
  "cd.f.highlight": ["Highlight", "Highlight"],
  "cd.f.lips": ["Môi", "Lips"],
  "cd.adapt": ["Chỉnh theo mặt bạn", "Fitting it to your face"],
  "det.note": ["Lưu ý.", "Note."],
  "det.pair": ["So sánh bảng màu nguyên bản và bản của bạn", "Original layout vs your version"],
  "det.orig": ["Bảng màu nguyên bản", "Original layout"],
  "det.origSub": ["Màu cộng đồng, trên mặt bạn", "Community colours, on your face"],
  "det.origLabel": ["Bảng màu nguyên bản trên khuôn mặt bạn", "Original layout on your face"],
  "det.mine": ["Chỉnh cho bạn", "Adapted for you"],
  "det.mineSub": ["Cùng nét, màu hợp {season}", "Same shapes, {season} colours"],
  "det.swapped": ["Đã đổi", "What changed"],
  "det.keep": ["Giữ nguyên:", "Kept:"],
  "det.goodColour": ["Màu hợp", "Suitable colour"],
  "det.faceNotes": ["Lưu ý cho mặt bạn", "Notes for your face"],
  "det.features": ["Nét chính", "Key features"],
  "det.steps": ["Các bước", "Steps"],
  "det.progress": ["{a}/{b} xong", "{a}/{b} done"],
  "det.stepsSub": ["Món tô xanh là món bạn đang có. Nhãn cạnh màu cho biết món đang có của bạn có khớp không.", "Blue-tinted products are ones you own. The chip beside each colour says whether your kit matches it."],
  "skin.inBuy": ["Có trong danh sách mua", "In To buy"],
  "skin.makeup": ["Trang điểm", "Makeup"],
  "skin.steps": ["{n} bước", "{n} steps"],
  "skin.notes": ["{n} lưu ý", "{n} notes"],
  "skin.mkSub": ["Cách đánh chi tiết nằm ở trang layout bạn chọn.", "Detailed technique lives on the look you choose."],
  "skin.oral": ["Uống", "Oral"],
  "skin.topical": ["Bôi", "Topical"],
  "skin.am": ["Sáng", "Morning"],
  "skin.amSub": ["{n} bước da", "{n} skincare steps"],
  "skin.noon": ["Trưa", "Midday"],
  "skin.noonSub": ["dặm lại khi ra ngoài", "top up when outdoors"],
  "skin.pm": ["Tối", "Night"],
  "skin.week": ["Tuần này", "This week"],
  "prof.eyebrow": ["Hồ sơ", "Profile"],
  "prof.title": ["Da, màu và khuôn mặt", "Skin, colour and face"],
  "prof.tone": ["Tông da", "Skin tone"],
  "prof.type": ["Loại da", "Skin type"],
  "prof.pc": ["Personal color", "Personal colour"],
  "prof.contrast": ["Độ tương phản", "Contrast"],
  "prof.shift": ["Màu lên da bạn thế nào", "How colour shifts on your skin"],
  "prof.s1": ["Đào lên hồng. Chọn hồng be, hồng nâu.", "Peach turns pink. Choose beige rose or rose brown."],
  "prof.s2": ["Cam lên đỏ cam. Chọn gạch hồng, đỏ nâu.", "Orange turns red-orange. Choose rose brick or brown red."],
  "prof.s3": ["Pastel quá nhạt so với độ đậm {season}, lên da gần như mất màu.", "Pastels are too light for {season} depth and almost vanish on skin."],
  "prof.face": ["Khuôn mặt", "Face"],
  "prof.rules": ["{n} lưu ý cho mặt bạn", "{n} rules for your face"],
  "prof.using": ["Đồ đang có", "Owned"],
  "prof.openInv": ["Mở Đồ đang có", "Open kit"],
  "prof.meds": ["Thuốc", "Medication"],
  "set.title": ["Cài đặt", "Settings"],
  "set.lang": ["Ngôn ngữ khi mở app", "Language when the app opens"],
  "set.langHelp": ["Mặc định là tiếng Việt. Nút VI | EN trên thanh đầu chỉ đổi ngôn ngữ của lần xem này; lần mở app sau dùng lựa chọn ở đây.", "Vietnamese by default. The VI | EN switch in the header changes this session only; the next time the app opens it uses this setting."],
  "set.saved": ["Đã lưu ngôn ngữ khi mở app", "Saved the language the app opens in"],
  "ck.v0": ["Hợp", "Suits"],
  "ck.v1": ["Tạm được", "Okay"],
  "ck.v2": ["Không hợp", "Doesn't suit"],
  "ck.sub": ["So với da và bảng màu {season} của bạn", "Against your skin and {season} palette"],
  "ck.pick": ["Chọn màu", "Pick a colour"],
  "ck.hex": ["Mã màu", "Hex code"],
  "ck.for": ["Dùng cho", "Used for"],
  "ck.skin": ["Da bạn", "Your skin"],
  "ck.test": ["Màu thử", "Test colour"],
  "ck.vsSkin": ["so với da", "vs skin"],
  "ck.onSkin": ["lên da", "on skin"],
  "ck.nearest": ["Gần nhất trong bảng {cat} của bạn", "Closest in your {cat} palette"],
  "ck.src": ["Từ Kiểm tra màu", "From Check a colour"],
  "ck.addManual": ["Thêm vào danh sách mua", "Add to shopping list"],
  "nav.today": ["Hôm nay", "Today"],
  "nav.palette": ["Bảng màu", "Palette"],
  "nav.layout": ["Layout", "Layouts"],
  "nav.skin": ["Da", "Skin"],
  "nav.check": ["Kiểm tra", "Check"],
  "nav.checkColor": ["Kiểm tra màu", "Check a colour"],
  "nav.profile": ["Hồ sơ của bạn", "Your profile"],
  "nav.nav": ["Điều hướng", "Navigation"],
  "lang.label": ["Ngôn ngữ", "Language"],
  "act.close": ["Đóng", "Close"],
  "act.edit": ["Sửa", "Edit"],
  "act.done": ["Xong", "Done"],
  "act.cancel": ["Hủy", "Cancel"],
  "act.remove": ["Bỏ", "Remove"],
  "act.check": ["Kiểm tra màu", "Check colour"],
  "act.view": ["Xem", "View"],
  "more": ["+{n}", "+{n}"],
  "shop.title": ["Danh sách mua", "Shopping list"],
  "shop.bag": ["Danh sách mua, {n} món", "Shopping list, {n} items"],
  "shop.subNeed": ["Tính từ Đồ đang có và các layout bạn muốn đánh", "Worked out from your kit and the layouts you want to wear"],
  "shop.subInv": ["Những gì bạn đang có. Có màu thì mới so được với layout.", "What you own. An item needs a colour before it can be compared."],
  "tab.need": ["Cần mua", "To buy"],
  "tab.inv": ["Đồ đang có", "My kit"],
  "need.stars": ["Layout muốn đánh · {n}", "Layouts you want · {n}"],
  "need.sum": ["{r}/{n} layout đã đủ đồ. Mua {k} món dưới đây theo thứ tự là đủ cả {n}.", "{r}/{n} layouts are covered. Buy the {k} items below, in order, to cover all {n}."],
  "need.sumDone": ["{r}/{n} layout đã đủ đồ. Không cần mua thêm đồ trang điểm.", "{r}/{n} layouts are covered. No more makeup to buy."],
  "need.none": ["Chưa chọn layout nào. Bấm Sửa để chọn.", "No layout chosen yet. Tap Edit to choose."],
  "need.allSet": ["Không cần mua thêm đồ trang điểm cho các layout đã chọn.", "Nothing more to buy for the layouts you chose."],
  "need.makeup": ["Trang điểm", "Makeup"],
  "need.order": ["món lấp nhiều layout nhất lên trước", "most layouts first"],
  "need.care": ["Chăm sóc da", "Skincare"],
  "need.fromRoutine": ["từ đánh giá routine", "from the routine review"],
  "need.manual": ["Tự thêm", "Added by hand"],
  "need.manualHint": ["Muốn mua món khác? Thêm từ Kiểm tra màu. Món tự thêm không ảnh hưởng thứ tự ở trên.", "Want something else? Add it from Check a colour. Hand-added items do not change the order above."],
  "note.unrec": ["Phấn mắt bạn đang dùng chưa có trong Đồ đang có.", "The eyeshadow you use is not in your kit yet."],
  "note.unrec2": ["Ghi màu trước khi mua để tránh mua trùng.", "Record their colours before buying so you do not buy a duplicate."],
  "note.unk": ["{name}: chưa có màu.", "{name}: no colour yet."],
  "note.unk2": ["Bước môi của {n} layout đang chờ màu này để kiểm tra.", "The lip step of {n} layouts is waiting for this colour."],
  "val.first": ["Mua 1 món → đủ đồ cho {n} layout: {names}", "Buy 1 item → {n} layouts covered: {names}"],
  "val.more": ["Cùng {i} món trên → đủ đồ thêm {n} layout: {names}", "With the {i} items above → {n} more layouts covered: {names}"],
  "val.fill": ["Lấp chỗ thiếu ở {n} layout; chưa đủ đồ layout nào nếu chỉ mua món này", "Fills a gap in {n} layouts; none is fully covered by this item alone"],
  "why.miss": ["Thiếu màu này cho: {names}", "Missing this colour for: {names}"],
  "near.has": ["Gần nhất bạn có: {reason}", "Closest you own: {reason}"],
  "why.diff": ["{own} của bạn {d} màu cần ({need}) → {cons}.", "Your {own} is {d} than the colour needed ({need}) → {cons}."],
  "why.close": ["{own} của bạn gần giống màu cần nhưng vẫn lệch màu khi lên da.", "Your {own} is close, but the difference still shows on skin."],
  "why.near": ["Hơi {d}, lên da khó thấy khác.", "Slightly {d}; hard to tell apart on skin."],
  "d.lighter": ["sáng hơn", "lighter"],
  "d.darker": ["đậm hơn", "deeper"],
  "d.warmer": ["ấm hơn (ngả cam)", "warmer (more orange)"],
  "d.pinker": ["hồng hơn", "pinker"],
  "d.vivid": ["rực hơn", "more vivid"],
  "d.muted": ["trầm hơn", "more muted"],
  "d.and": [" và ", " and "],
  "c.lighter": ["lên da sẽ nhạt, dễ chìm", "it will look washed out"],
  "c.darker": ["lên da sẽ đậm và nặng hơn", "it will look heavier"],
  "c.warmer": ["lên da sẽ ngả cam", "it will turn orange on skin"],
  "c.pinker": ["lên da sẽ ngả hồng", "it will turn pink on skin"],
  "c.vivid": ["lên da sẽ rực hơn layout cần", "it will look louder than the layout"],
  "c.muted": ["lên da sẽ xỉn hơn", "it will look dull"],
  "pair.tip": ["Trái: màu cần · Phải: màu của bạn", "Left: needed · Right: yours"],
  "need.default": ["Mặc định chọn các layout có mức hợp “Hợp sẵn”. Bấm Sửa để chọn layout khác.", "Layouts rated “Natural fit” are chosen by default. Tap Edit to change."],
  "fit.prefix": ["Hợp với bạn", "Fit"],
  "fit.tip": ["Hợp với bạn: mức hợp của layout này với da và khuôn mặt bạn, không phải tên layout.", "Fit: how well this layout suits your skin and face. It is not the layout's name."],
  "near.none": ["Bạn chưa có {cat} nào để so.", "Your kit has no {cat} to compare yet."],
  "buy.unrecorded": ["Nếu {cat} bạn đang dùng có màu này thì không cần mua: ghi vào Đồ đang có để kiểm tra.", "If your current {cat} already has this colour, skip it: record it in your kit to check."],
  "grp.eye": ["Bảng mắt", "Eye palette"],
  "grp.face": ["Bảng tạo khối, highlight", "Contour and highlight palette"],
  "grp.blush": ["Bảng má nhiều ô", "Multi-pan blush palette"],
  "req.eye": ["Cần một bảng mắt có các màu sau:", "You need an eye palette with these colours:"],
  "req.face": ["Cần một bảng tạo khối, bắt sáng có các màu sau:", "You need a contour and highlight palette with these colours:"],
  "req.blush": ["Cần một bảng má có các màu sau:", "You need a blush palette with these colours:"],
  "req.must": ["Cần có", "Must have"],
  "req.nice": ["Có thì tốt", "Nice to have"],
  "req.for": ["{n} layout: {names}", "{n} layouts: {names}"],
  "req.more": ["Bảng nhiều ô hơn cũng được, miễn có đủ các màu trên; ô thừa không sao. “Cần có” là màu nhiều layout cần nhất.", "A palette with more pans is fine as long as it has these colours; extra pans do no harm. “Must have” marks the colours most layouts need."],
  "r.base": ["màu nền mắt", "lid base"],
  "r.main": ["màu chính", "main colour"],
  "r.depth": ["màu đậm", "depth"],
  "r.liner": ["kẻ mắt", "liner"],
  "r.shimmer": ["nhũ", "fine shimmer"],
  "r.matte": ["bắt sáng lì", "matte highlight"],
  "r.glow": ["highlight", "highlight"],
  "r.contour": ["tạo khối", "contour"],
  "r.cream": ["má dạng kem", "cream blush"],
  "r.powder": ["má dạng phấn", "powder blush"],
  "buy.palette": ["Bảng mắt {n} ô", "{n}-pan eye palette"],
  "buy.pans": ["Một bảng gồm", "One palette with"],
  "buy.cream": ["Chọn dạng kem: dùng được làm tint môi.", "Pick a cream formula: it also works as a lip tint."],
  "cum": ["{a}/{b} đủ đồ", "{a}/{b} covered"],
  "act.bought": ["Đã mua", "Bought"],
  "act.routine": ["Xem routine", "View routine"],
  "act.copyList": ["Chép danh sách", "Copy list"],
  "act.record": ["Ghi vào Đồ đang có", "Add to kit"],
  "act.addColor": ["Thêm màu", "Add colour"],
  "act.realColor": ["Lấy màu thật", "Sample real colour"],
  "act.photo": ["Lấy từ ảnh", "From photo"],
  "act.saveInv": ["Lưu vào Đồ đang có", "Save to kit"],
  "act.saveColor": ["Lưu màu", "Save colour"],
  "act.addItem": ["+ Thêm món", "+ Add item"],
  "form.buy": ["Màu thật của món bạn đã mua? Chọn màu hoặc lấy từ ảnh swatch; mặc định là màu gợi ý.", "What colour did you actually buy? Pick it or sample a swatch photo; it starts at the suggested colour."],
  "form.edit": ["Chọn màu hoặc lấy từ ảnh swatch chụp dưới ánh sáng ban ngày.", "Pick the colour or sample a swatch photo taken in daylight."],
  "form.tint": ["Mỗi cây tint là một màu. Thêm màu cho cây bạn dùng nhiều nhất trước.", "Each tint is one colour. Start with the one you use most."],
  "form.oneTint": ["Cây tint", "One tint"],
  "toast.copied": ["Đã chép {n} món", "Copied {n} items"],
  "toast.boughtReady": ["Đã thêm vào Đồ đang có. Đủ đồ thêm: {names}", "Added to your kit. Now covered: {names}"],
  "toast.bought": ["Đã thêm vào Đồ đang có. Đã tính lại các layout.", "Added to your kit. Layouts recalculated."],
  "toast.color": ["Đã lưu màu. {n} layout được kiểm tra lại.", "Colour saved. {n} layouts rechecked."],
  "toast.star": ["Đã thêm {n} món thiếu của {name} vào danh sách mua", "Added {name}'s {n} missing items to To buy"],
  "toast.unstar": ["Đã bỏ {name} khỏi layout muốn đánh", "Removed {name} from your layouts"],
  "toast.manual": ["Đã thêm vào danh sách mua, mục Tự thêm", "Added to To buy, under Added by hand"],
  "st.ok": ["Trùng màu", "Practically identical"],
  "st.near": ["Gần giống – dùng được", "Close – fine to use"],
  "st.miss": ["Lệch màu – cần màu khác", "Clearly different – needs another colour"],
  "st.unk": ["Chưa có màu – thêm màu để so", "No colour yet – add one to compare"],
  "ready.ok": ["Đủ đồ", "Ready"],
  "ready.miss": ["Thiếu {n}", "Missing {n}"],
  "ready.unk": ["Chờ màu", "Needs colour"],
  "sum.ready": ["Đủ đồ", "You have everything"],
  "sum.readyEst": ["Đủ đồ (có màu ước lượng)", "You have everything (some colours estimated)"],
  "sum.miss": ["Thiếu {n} món", "Missing {n} items"],
  "sum.miss1": ["Thiếu 1 món", "Missing 1 item"],
  "sum.alsoUnk": ["{m} món chưa biết màu", "{m} items without a colour"],
  "sum.alsoUnk1": ["1 món chưa biết màu", "1 item without a colour"],
  "sum.unk": ["Cần thêm màu cho {m} món đang có để kiểm tra", "Add a colour to {m} items you own to check"],
  "sum.unk1": ["Cần thêm màu cho 1 món đang có để kiểm tra", "Add a colour to 1 item you own to check"],
  "inv.lede": ["{n} sản phẩm · {m} chưa có màu. Món chưa có màu thì không so được với layout.", "{n} products · {m} without a colour. An item without a colour cannot be compared with a layout."],
  "inv.noColor": ["Chưa có màu, chụp swatch để thêm", "No colour yet, photograph a swatch to add one"],
  "inv.clear": ["Trong suốt, không có màu", "Clear, no colour"],
  "inv.cheek": ["dùng được cho má", "also works on cheeks"],
  "inv.brandUnv": ["chưa xác minh hãng", "brand not verified"],
  "scope.note": ["Chưa tính {cats}: mục Đồ đang có chưa có món nào thuộc nhóm này.", "Not counted: {cats}. Your kit has nothing in these groups yet."],
  "note.unkAll": ["{n} món chưa có màu nên chưa so được: {names}.", "{n} items have no colour yet, so they cannot be compared: {names}."],
  "note.unkAll1": ["1 món chưa có màu nên chưa so được: {names}.", "1 item has no colour yet, so it cannot be compared: {names}."],
  "maybe.have": ["Có thể đã có, cần màu để xác nhận: {names}.", "You may already own this; add a colour to confirm: {names}."],
  "ofin.gloss": ["bóng", "glossy"],
  "ofin.matte": ["lì", "matte"],
  "ofin.satin": ["lì hoặc satin", "matte or satin"],
  "ofin.velvet": ["lì mịn", "velvet matte"],
  "ofin.shimmer": ["nhũ", "shimmer"],
  "ofin.clear": ["trong suốt", "clear"],
  "pan.o.highlight": ["ô sáng", "light pan"],
  "pan.o.transition": ["ô chuyển", "transition pan"],
  "pan.o.crease": ["ô nếp mí", "crease pan"],
  "pan.o.deepen": ["ô đậm", "deep pan"],
  "pan.o.contour": ["ô tạo khối", "contour pan"],
  "cat.liner": ["Chì kẻ mắt", "Eyeliner"],
  "inv.blocks": ["{n} layout đang chờ màu này.", "Blocking {n} layouts."],
  "inv.noBlock": ["Chưa có layout nào đang chờ màu này.", "Not blocking any layout."],
  "inv.used": ["dùng trong {n} layout", "used in {n} layouts"],
  "inv.bought": ["Vừa mua", "Just bought"],
  "inv.tints": ["Son tint bóng đang có", "Glossy lip tints you own"],
  "inv.tintsOther": ["Các tint bóng khác", "Your other glossy tints"],
  "inv.tintShort": ["Tint bóng", "Glossy tint"],
  "own.tint": ["son tint bóng", "glossy lip tints"],
  "inv.tintRec": ["Tint bóng (đã ghi màu)", "Glossy tint (colour recorded)"],
  "inv.tintRecS": ["Tint bóng đã ghi", "Recorded tint"],
  "inv.unrec.mat": ["Phấn mắt bạn đang dùng", "The eyeshadow you use"],
  "inv.unrec.ma": ["Phấn má bạn đang dùng", "The blush you use"],
  "inv.unrecWhy": ["Chưa ghi. Gợi ý mua phấn mắt có thể trùng đồ bạn đã có.", "Not recorded. Eyeshadow suggestions may duplicate what you own."],
  "tag.est": ["ước lượng", "estimated"],
  "inv.noNeed": ["Không cần màu", "No colour needed"],
  "st.have": ["Có sẵn", "You have it"],
  "mine.have": ["Dùng {name}: bước này không cần so màu.", "Use {name}: this step needs no colour match."],
  "cat.khoa": ["Khóa nền", "Setting spray"],
  "pan.jHlMatte": ["ô bắt sáng lì kem", "matte cream highlight"],
  "pan.jHlShim": ["ô bắt sáng nhũ champagne", "champagne shimmer highlight"],
  "pan.jKhoiLight": ["ô tạo khối taupe nhạt", "light taupe contour"],
  "pan.jKhoiDeep": ["ô tạo khối nâu ấm đậm", "deep warm-brown contour"],
  "tag.estHint": ["màu ước lượng – chụp swatch để chính xác hơn", "estimated colour – swatch it for accuracy"],
  "c.may.lighter": ["hợp layout nhẹ; layout mày đậm cần màu tối hơn", "fine for soft layouts; bold-brow layouts need a deeper colour"],
  "c.may.warmer": ["mày lên nâu đỏ; layout cần {need} nên chọn màu xám hơn", "brows read red-brown; this layout wants {need}, so pick a greyer shade"],
  "c.ma.warmer": ["dễ ngả cam đỏ; hợp layout tông đào, không thay được {need}", "it can turn orange-red; fine for peach layouts, not a substitute for {need}"],
  "c.ma.lighter": ["lên má nhạt, phải đánh nhiều lớp mới ra màu {need}", "too light on the cheek; it needs several layers to reach {need}"],
  "c.khoi.warmer": ["dễ thành vệt bronze cam thay vì bóng đổ", "it reads as an orange bronze stripe, not a shadow"],
  "c.che.warmer": ["dưới lớp nền dễ lộ mảng cam", "it can show as an orange patch under the base"],
  "n.may.lighter": ["Hơi sáng hơn, đánh nhẹ tay vẫn hợp.", "Slightly lighter; fine with a light hand."],
  "pan.peach": ["ô đào", "peach pan"],
  "pan.dark": ["ô tông da đậm", "deeper pan"],
  "pan.light": ["ô tông da nhạt", "lighter pan"],
  "pan.n": ["ô {n}", "pan {n}"],
  "cat.nen": ["Kem nền", "Foundation"],
  "cat.che": ["Che khuyết điểm", "Concealer"],
  "cat.phu": ["Phấn phủ", "Setting powder"],
  "cat.ma": ["Má hồng", "Blush"],
  "cat.son": ["Son", "Lip colour"],
  "cat.chi": ["Chì kẻ môi", "Lip liner"],
  "cat.mat": ["Phấn mắt", "Eyeshadow"],
  "cat.khoi": ["Tạo khối", "Contour"],
  "cat.hl": ["Highlight", "Highlight"],
  "cat.may": ["Chân mày", "Brow"],
  "cat.care": ["Chăm sóc da", "Skincare"],
  "x.cheNen": ["che khuyết điểm làm nền vùng nhỏ", "concealer as spot foundation"],
  "x.nenChe": ["kem nền làm che khuyết điểm", "foundation as concealer"],
  "x.blushEye": ["phấn má làm màu mắt chính", "blush as main eye colour"],
  "x.contourEye": ["tạo khối làm màu đậm cho mắt", "contour as eye depth"],
  "x.eyeContour": ["phấn mắt làm tạo khối", "eyeshadow as contour"],
  "x.hlBase": ["highlight lì làm màu nền mắt", "matte highlight as lid base"],
  "x.baseHl": ["màu nền mắt làm highlight lì", "lid base as matte highlight"],
  "x.cheHl": ["che khuyết điểm sáng làm highlight lì", "light concealer as matte highlight"],
  "x.tintBlush": ["tint môi làm má kem", "lip tint as cream blush"],
  "x.blushTint": ["má kem làm tint môi", "cream blush as lip tint"],
  "x.linerLip": ["chì kẻ môi tô kín lòng môi", "lip liner filled in"],
  "x.browLiner": ["chì mày đậm làm kẻ mắt", "dark brow pencil as liner"],
  "x.eyeLiner": ["phấn mắt đậm làm kẻ mắt", "dark eyeshadow as liner"],
  "mine.title": ["Đồ của bạn cho layout này", "Your kit for this layout"],
  "mine.star": ["Muốn đánh", "Want to wear"],
  "mine.counts": ["{a}/{b} bước có màu trùng trong đồ đang có", "{a}/{b} steps have a practically identical colour in your kit"],
  "mine.okN": ["{n} bước có màu trùng", "{n} steps with a practically identical colour"],
  "mine.ok": ["Dùng {name}: nhìn không ra khác biệt", "Use {name}: you cannot tell them apart"],
  "mine.near": ["Dùng {name}.", "Use {name}."],
  "mine.cross": ["Dùng {name} ({rule}).", "Use {name} ({rule})."],
  "mine.unk": ["{name} chưa có màu nên chưa so được", "{name} has no colour yet, so it cannot be compared"],
  "mine.missNone": ["Bạn chưa có {cat}", "No {cat} in your kit"],
  "mine.add": ["Thêm {n} món thiếu vào danh sách mua", "Add {n} missing items to To buy"],
  "mine.inList": ["{n} món thiếu đã ở trong danh sách mua", "{n} missing items are in To buy"],
  "mine.sameAs": ["Cùng màu với bước {label}, tính là 1 món", "Same colour as {label}; counted once"],
  "act.add": ["+ Thêm", "+ Add"],
  "mine.addColor": ["Thêm màu: {name}", "Add colour: {name}"],
  "loc.hanoi": ["Hà Nội / miền Bắc", "Hanoi / the North"],
  "loc.hcm": ["TP.HCM / miền Nam", "Ho Chi Minh City / the South"],
  "loc.danang": ["Đà Nẵng / miền Trung", "Da Nang / the Centre"],
  "loc.dalat": ["Đà Lạt", "Da Lat"],
  "loc.other": ["Khác", "Other"],
  "clim.humid": ["khí hậu nóng ẩm", "hot, humid climate"],
  "clim.cold": ["khí hậu khô lạnh", "cold, dry climate"],
  "clim.mild": ["khí hậu ôn hòa", "mild climate"],
  "climS.humid": ["Nóng ẩm", "Hot, humid"],
  "climS.cold": ["Khô lạnh", "Cold, dry"],
  "climS.mild": ["Ôn hòa", "Mild"],
  "sea.n.winter": ["đông hanh khô", "dry winter"],
  "sea.n.spring": ["xuân nồm ẩm", "humid spring"],
  "sea.n.summer": ["hè nóng ẩm", "hot, humid summer"],
  "sea.n.autumn": ["thu, đang chuyển mùa", "autumn, changing season"],
  "sea.s.rainy": ["mùa mưa, nóng ẩm", "rainy season, hot and humid"],
  "sea.s.dry": ["mùa khô, nắng nóng", "dry season, hot and sunny"],
  "sea.c.rainy": ["mùa mưa bão", "rainy and storm season"],
  "sea.c.spring": ["xuân khô mát", "dry, mild spring"],
  "sea.c.summer": ["hè nắng nóng", "hot, sunny summer"],
  "sea.h.dry": ["mùa khô, se lạnh", "dry, chilly season"],
  "sea.h.rainy": ["mùa mưa, mát ẩm", "rainy, cool season"],
  "sea.o.humid": ["nóng ẩm", "hot and humid"],
  "sea.o.cold": ["khô lạnh", "cold and dry"],
  "sea.o.mild": ["ôn hòa", "mild"],
  "today.date": ["{weekday}, {day} tháng {month} · {place}", "{weekday}, {day} {month} · {place}"],
  "lede.humid": ["Trời nóng ẩm, da đổ dầu nhanh. Nền mỏng, lâu trôi, chỉ phủ phấn chữ T.", "Hot and humid: skin gets oily fast. Thin, long-wear base, powder only the T-zone."],
  "lede.hot": ["Nắng nóng, ít mưa. Nền mỏng, ít lớp, chọn chất lâu trôi.", "Hot and sunny with little rain. A thin base with few layers, long-wear formulas."],
  "lede.dry": ["Trời hanh khô, nền dễ mốc. Nền satin lớp mỏng, phủ phấn ít.", "Dry weather: the base can turn patchy. A thin satin base, little powder."],
  "lede.mixed": ["Đang chuyển mùa: sáng tối hanh, trưa còn nóng. Nền mỏng, chỉ phủ phấn chữ T.", "The season is turning: dry mornings and evenings, still hot at noon. Keep the base thin and powder only the T-zone."],
  "lede.cool": ["Trời mát và ẩm. Nền satin, màu ấm trầm lên rõ; kẻ mắt chống nước khi mưa.", "Cool and damp. A satin base; warm, deep colours show well; waterproof liner on rainy days."],
  "sug.humid": ["Trời nóng ẩm hợp layout nhẹ, lâu trôi.", "Humid weather suits light, long-wear layouts."],
  "sug.hot": ["Nắng nóng hợp layout nhẹ, ít lớp.", "Hot sun suits light layouts with few layers."],
  "sug.dry": ["Trời hanh hợp tông nâu ấm, chất satin.", "Dry weather suits warm browns in a satin finish."],
  "sug.mixed": ["Mùa chuyển hợp tông nâu.", "A changing season suits browns."],
  "sug.cool": ["Trời mát hợp tông nâu và đỏ trầm.", "Cool weather suits browns and deep reds."],
  "pal.season": ["Theo mùa ở {place}", "Seasons in {place}"],
  "pal.whenHumid": ["Khi trời nóng ẩm.", "When it is hot and humid."],
  "pal.whenDry": ["Khi trời hanh khô, se lạnh.", "When it is dry or chilly."],
  "pal.now": ["Đang áp dụng", "Applies now"],
  "pal.both": ["Đang chuyển mùa ({season}): dùng cả hai.", "Changing season ({season}): use both."],
  "set.loc": ["Nơi bạn sống", "Where you live"],
  "set.locHelp": ["Mẹo trang điểm theo mùa ở Hôm nay và Bảng màu dùng khí hậu nơi này. Bây giờ: {season}.", "Seasonal makeup tips on Today and Palette use this climate. Now: {season}."],
  "set.clim": ["Kiểu khí hậu", "Climate type"],
  "set.locSaved": ["Đã lưu nơi bạn sống", "Saved where you live"],
  "vw.title": ["Độ đậm nét mặt", "Visual weight"],
  "vw.hair": ["Tóc", "Hair"],
  "vw.brows": ["Mày", "Brows"],
  "vw.eyes": ["Mắt", "Eyes"],
  "vw.lips": ["Môi", "Lips"],
  "vw.jaw": ["Hàm", "Jaw"],
  "vw.l1": ["rất nhạt", "very light"],
  "vw.l2": ["nhạt", "light"],
  "vw.l3": ["vừa", "medium"],
  "vw.l4": ["khá đậm", "fairly heavy"],
  "vw.l5": ["đậm", "heavy"],
  "pc.title": ["Màu của bạn", "Your colours"],
  "pc.sub": ["Màu thật của da, môi, mày, tóc và mắt. Kiểm tra màu so son với cả môi thật và da, so màu mày với mày và tóc.", "Your real skin, lip, brow, hair and eye colours. Check a colour compares lip colour with your natural lips and skin, and brow colour with your brows and hair."],
  "pc.skin": ["Da (mộc)", "Skin (bare)"],
  "pc.found": ["Kem nền", "Foundation"],
  "pc.lip": ["Môi tự nhiên", "Natural lips"],
  "pc.brow": ["Chân mày", "Brows"],
  "pc.hair": ["Tóc", "Hair"],
  "pc.iris": ["Mắt (tròng)", "Eyes (iris)"],
  "pc.skinSub": ["Chuẩn để so cho nền, má, highlight, tạo khối", "The reference for base, blush, highlight and contour"],
  "pc.foundSub": ["Kem nền đang dùng, so với da", "The foundation you use, compared with your skin"],
  "pc.lipSub": ["Màu môi thật; chuẩn để so cho son", "Your natural lip colour; the reference for lip colour"],
  "pc.browSub": ["Chuẩn để so cho chì mày, phấn mày và kẻ mắt", "The reference for brow pencil, brow powder and liner"],
  "pc.irisSub": ["Chuẩn để so cho kẻ mắt và mascara", "Reference for liner and mascara"],
  "pc.hex": ["Mã màu", "Hex codes"],
  "pc.cMain": ["chính", "main"],
  "pc.cRim": ["viền", "rim"],
  "pc.cHead": ["đầu mày", "head"],
  "pc.cDark": ["đậm nhất", "darkest"],
  "pk.title": ["Chọn màu", "Pick a colour"],
  "pc.edit": ["Sửa", "Edit"],
  "pc.editAria": ["Sửa màu: {name}", "Edit colour: {name}"],
  "pc.preview": ["Xem cạnh nhau", "Side by side"],
  "pc.pvSkinLip": ["Da | môi", "Skin | lips"],
  "pc.pvLip": ["Môi trên da", "Lips on skin"],
  "pc.pvBrow": ["Mày trên da", "Brows on skin"],
  "pc.pvHair": ["Tóc cạnh da", "Hair by skin"],
  "pc.pvHint": ["Trông giống ngoài đời chưa? Nếu lệch, sửa ở hàng tương ứng.", "Does it look like you? If not, edit that row."],
  "pc.auto": ["tên gợi ý", "suggested name"],
  "pk.main": ["Màu chính", "Main colour"],
  "pk.lipRim": ["Viền môi (tùy chọn)", "Rim (optional)"],
  "pk.browHead": ["Đầu mày", "Brow head"],
  "pk.browDark": ["Phần đậm nhất", "Darkest part"],
  "pk.sub": ["Dùng cách nào cũng được; dải xem trước đổi ngay.", "Use any of the three ways; the preview updates as you go."],
  "pk.parts": ["Phần đang sửa", "Part being edited"],
  "pk.before": ["Trước", "Before"],
  "pk.after": ["Sau", "After"],
  "pk.tabs": ["Cách chọn màu", "How to pick"],
  "pk.tabPick": ["Bảng màu", "Picker"],
  "pk.tabPhoto": ["Từ ảnh", "From photo"],
  "pk.tabPreset": ["Màu gợi ý", "Presets"],
  "pk.open": ["Mở bảng màu", "Open colour picker"],
  "pk.fine": ["Chỉnh từng chút", "Fine-tune"],
  "pk.fineHint": ["Mỗi lần bấm đổi một chút. Sáng/tối là độ sáng; rực/trầm là nhiều/ít sắc.", "Each tap is a small step. Lighter/darker is brightness; vivid/muted is how much colour."],
  "pk.lighter": ["Sáng hơn", "Lighter"],
  "pk.darker": ["Tối hơn", "Darker"],
  "pk.warmer": ["Ấm hơn", "Warmer"],
  "pk.cooler": ["Lạnh hơn", "Cooler"],
  "pk.richer": ["Rực hơn", "More vivid"],
  "pk.softer": ["Trầm hơn", "More muted"],
  "pk.reset": ["Về màu cũ", "Back to original"],
  "pk.upload": ["Tải ảnh lên", "Upload a photo"],
  "pk.light": ["Chụp gần cửa sổ, ánh sáng tự nhiên ban ngày; không flash, không filter, mặt mộc. Đèn vàng làm màu ấm hơn thật.", "Shoot by a window in daylight: no flash, no filter, bare face. Warm bulbs make colour look warmer than it is."],
  "pk.photoAria": ["Ảnh để lấy màu. Chạm vào ảnh, hoặc dùng phím mũi tên để dời điểm và Enter để lấy.", "Photo to sample from. Tap it, or move the point with the arrow keys and press Enter."],
  "pk.demo": ["Ảnh minh họa. Tải ảnh của bạn để lấy màu thật.", "Illustration. Upload your own photo to sample real colour."],
  "pk.avg": ["Trung bình 5×5 điểm ảnh", "5×5 pixel average"],
  "pk.tap": ["Chạm vào ảnh để lấy màu ở điểm này", "Tap the photo to take the colour here"],
  "pk.loupe": ["Kính lúp: ô vuông giữa là 5×5 điểm ảnh được lấy trung bình", "Loupe: the centre square is the 5×5 pixels averaged"],
  "pk.sampled": ["Đã lấy màu: {name}", "Sampled: {name}"],
  "pk.presetHint": ["Chọn tông gần nhất, rồi chỉnh từng chút ở tab Bảng màu.", "Pick the closest tone, then fine-tune on the Picker tab."],
  "pk.save": ["Lưu màu", "Save colour"],
  "pk.saved": ["Đã lưu. Kiểm tra màu dùng màu mới.", "Saved. Check a colour now uses it."],
  "ck.subLip": ["So với môi thật và da của bạn", "Against your natural lips and skin"],
  "ck.subBrow": ["So với mày và tóc của bạn", "Against your brows and hair"],
  "ck.samples": ["Thử nhanh", "Quick tests"],
  "ck.finish": ["Chất son", "Finish"],
  "ck.ptype": ["Loại", "Type"],
  "ck.cover": ["phủ ~{n}%", "~{n}% cover"],
  "fin.tint": ["Tint", "Tint"],
  "fin.gloss": ["Tint bóng", "Gloss tint"],
  "fin.velvet": ["Velvet", "Velvet"],
  "fin.matte": ["Lì", "Matte"],
  "fin.liner": ["Chì kẻ môi", "Lip liner"],
  "fin.pencil": ["Chì mày", "Brow pencil"],
  "fin.powder": ["Phấn mày", "Brow powder"],
  "fin.eyeliner": ["Chì kẻ mắt", "Eye pencil"],
  "ck.natLip": ["Môi thật", "Natural lips"],
  "ck.brow": ["Mày bạn", "Your brows"],
  "ck.hair": ["Tóc", "Hair"],
  "ck.rimWord": ["viền môi", "lip rim"],
  "ck.onLips": ["Trên môi bạn", "On your lips"],
  "ck.onLipsSub": ["Màu thử phủ lên môi thật theo độ phủ của chất son; son trong để viền môi nhìn xuyên qua.", "The test colour laid over your natural lips at the finish's coverage; a sheer formula lets the lip rim show through."],
  "ck.bare": ["Môi thật", "Bare lips"],
  "ck.with": ["Có son", "With colour"],
  "ck.withLined": ["Có son, đã kẻ viền môi", "With colour, lined"],
  "ck.lined": ["Kẻ viền môi trước", "Line the lips first"],
  "ck.onBrows": ["Trên mày bạn", "On your brows"],
  "ck.onBrowsSub": ["Nét màu thử chen giữa sợi mày thật; dải trên cùng là màu tóc.", "Test strokes between your real brow hairs; the top band is your hair colour."],
  "ck.browBare": ["Mày thật", "Bare brows"],
  "ck.browWith": ["Có màu thử", "With test colour"],
  "ck.vLiner": ["Kẻ viền môi", "Liner"],
  "ck.tagLight": ["Hợp layout nhẹ", "For light looks"],
  "ck.tagHead": ["Hợp đầu mày", "For the brow head"],
  "ck.tagRim": ["Cần kẻ viền môi", "Line the rim"],
  "cr.depth": ["Độ đậm so với môi thật", "Depth vs natural lips"],
  "cr.tone": ["Undertone so với da", "Undertone vs skin"],
  "cr.rim": ["Viền môi", "Lip rim"],
  "cr.light": ["Độ sáng so với mày và tóc", "Lightness vs brows and hair"],
  "cr.warm": ["Sắc ấm, lạnh", "Warmth"],
  "cr.use": ["Cách dùng", "How to use"],
  "cs.0": ["Hợp", "Pass"],
  "cs.1": ["Lưu ý", "Note"],
  "cs.2": ["Không hợp", "Fail"],
  "cs.f": ["Cần thêm bước", "Needs a step"],
  "cs.n": ["Thông tin", "Info"],
  "ck.hLipOk": ["Đúng mức đậm, đúng undertone.", "Right depth, right undertone."],
  "ck.hLipOkRim": ["Đúng mức đậm, đúng undertone; kẻ viền môi trước vì son trong.", "Right depth and undertone; line the rim first because it is sheer."],
  "lp.lighter": ["Nhạt hơn môi thật khoảng {n} bậc: môi nhợt, mặt thiếu điểm nhấn.", "About {n} step(s) paler than your natural lips: lips look washed out."],
  "lp.same": ["Gần như bằng màu môi thật: không thêm trọng lượng cho nửa dưới khuôn mặt.", "Almost your natural lip colour: adds no weight to the lower face."],
  "lp.half": ["Đậm hơn môi thật chưa tới 1 bậc: hơi nhạt; đánh 2 lớp để tới mức 1–2 bậc.", "Less than a step deeper than your lips: a little light; two layers reach the 1–2 step target."],
  "lp.target": ["Đậm hơn môi thật khoảng {n} bậc: đúng mức 1–2 bậc.", "About {n} steps deeper than your lips: inside the 1–2 step target."],
  "lp.deep": ["Đậm hơn môi thật khoảng {n} bậc, quá mức 1–2 bậc. Ban ngày đánh 1 lớp mỏng hoặc tán gradient; buổi tối để nguyên.", "About {n} steps deeper than your lips, past the 1–2 step target. By day, one thin layer or a gradient; full strength at night."],
  "lp.vdeep": ["Đậm hơn môi thật hơn 3 bậc: chỉ hợp buổi tối hoặc tiệc.", "More than 3 steps deeper than your lips: evenings and parties only."],
  "lt.good": ["Đỏ nâu, hồng nâu, ít vàng: hợp {season}.", "Brown red or rose brown with little yellow: suits {season}."],
  "lt.orange": ["Ngả cam: dễ lên đỏ cam, răng trông vàng hơn.", "Leans orange: can turn red-orange and make teeth look yellower."],
  "lt.yellow": ["Ngả vàng: {season} hợp phía ít vàng hơn.", "Leans yellow: {season} suits the less-yellow side."],
  "lt.cool": ["Hồng tím lạnh: bị nổi, lệch hẳn màu da ấm và làm da ngả vàng.", "Cool purple-pink: sits apart from warm skin and makes it look yellow."],
  "lt.grey": ["Xám, ít sắc: làm môi nhợt.", "Greyish: makes lips look pale."],
  "lt.odd": ["Màu thời trang, không phải màu son hằng ngày.", "A fashion shade, not an everyday lip colour."],
  "lt.nude": ["Be đào, ấm hơn viền môi: phủ lên viền sẽ trung hòa ánh lạnh của viền.", "Peachy beige, warmer than the lip rim: it neutralises a cool rim."],
  "lr.shows": ["{fin} trong (phủ ~{n}%): {rim} vẫn lộ quanh môi. Kẻ viền môi hoặc chấm che khuyết điểm mỏng trước.", "{fin} is sheer (~{n}% cover): the {rim} still shows round the edge. Line the lips or dab a thin concealer first."],
  "lr.covered": ["Phủ đủ dày: {rim} không lộ, không cần kẻ viền môi.", "Covers enough: the {rim} will not show; no liner needed."],
  "lr.fixes": ["Che được {rim}: sau khi kẻ, viền gần như cùng màu lòng môi.", "Hides the {rim}: once lined, the edge matches the centre."],
  "lr.none": ["Chưa nhập màu viền môi; bỏ qua bước này.", "No rim colour saved; this check is skipped."],
  "ll.main": ["Gần màu môi thật, sáng hơn khoảng {n} bậc: dùng để kẻ viền môi, không làm son chính.", "Close to your natural lips, about {n} step(s) lighter: use it to line, not as the main colour."],
  "ll.dark": ["Chì kẻ môi đậm hơn môi thật: hợp viền ombre hoặc overline nhẹ, không che được {rim}.", "Darker than your lips: good for an ombré edge or a slight overline, but it will not hide the {rim}."],
  "ll.closeSheer": ["Gần như màu môi thật: hợp làm lớp lót hơn là son chính.", "Almost your natural lip colour: better as a base layer than as lip colour."],
  "bl.tooDark": ["Đậm bằng tóc: mày dễ cứng và nặng mặt.", "As dark as your hair: brows turn harsh and heavy."],
  "bl.match": ["Khớp mày thật, hoặc nhạt hơn tóc nửa bậc: đúng mục tiêu.", "Matches your brows, or half a step lighter than your hair: on target."],
  "bl.head": ["Sáng hơn thân mày khoảng {n} bậc nhưng khớp đầu mày: dùng cho đầu mày và chỗ thưa; thân và đuôi cần màu đậm hơn.", "About {n} steps lighter than the brow body but matches the head: use it for the head and gaps; the body and tail need a darker shade."],
  "bl.light": ["Sáng hơn mày thật khoảng {n} bậc, sáng hơn cả đầu mày: mày nhìn nhạt và nâu.", "About {n} steps lighter than your brows, lighter even than the head: brows read soft and brown."],
  "bl.vlight": ["Quá sáng so với mày thật: mày mất nét.", "Far too light for your brows: they lose definition."],
  "bw.cool": ["Xám lạnh, lên mặt bị nổi, lệch hẳn màu da; chỉ dùng cho layout tông lạnh.", "A cool grey that detaches from your skin and stands out from the face; only for cool-tone layouts."],
  "bw.coolOk": ["Xám lạnh, nhưng layout tông lạnh thì hợp.", "A cool grey, which works in a cool-tone layout."],
  "ck.vCool": ["Không hợp với mặt bạn", "Doesn't suit your face"],
  "ck.tagCool": ["quá lạnh", "off cool"],
  "ck.coolLayout": ["Layout tông lạnh", "Cool-tone layout"],
  "bw.neutral": ["Trung tính, ít sắc ấm: khớp ánh xám của mày.", "Neutral with little warmth: matches the grey cast of your brows."],
  "bw.warm": ["Ấm hơn mày thật: nhìn nâu rõ hơn.", "Warmer than your brows: reads clearly brown."],
  "bw.brown": ["Nâu ấm rõ, lệch với màu mày thật: nhìn như mày nhuộm.", "Clearly warm brown against your real brows: looks dyed."],
  "bw.red": ["Ngả đỏ nâu: lệch với màu tóc, nhìn như mày nhuộm.", "Leans red-brown: clashes with your hair and looks dyed."],
  "bu.light": ["Chỉ cho layout nhẹ (Clean girl, sương sương): tán mỏng, chải lại bằng gel mày.", "Light looks only (Clean girl, no-makeup): sheer, brushed through with brow gel."],
  "bu.eyeliner": ["Chì kẻ mắt mềm hơn chì mày, dễ lem trên da dầu: kẻ nét mảnh, khóa bằng gel mày trong.", "An eye pencil is softer than a brow pencil and smudges on oily skin: fine strokes, set with clear gel."],
  "bu.fill": ["Chỉ lấp chỗ thưa, không tô đậm thêm so với mày thật.", "Fill gaps only; do not go darker than your real brows."],
  "today.routineLine": ["Sáng {a} bước · tối {b} bước.", "Morning: {a} steps · night: {b} steps."],
  "prof.pcV": ["{season}", "{season}"],
  "pc.hairSub": ["Chỉ làm chuẩn để so cho màu mày và kẻ mắt", "Only a reference for brow and liner colour"],
  "ck.liner": ["Chì kẻ môi", "Lip liner"],
  "skin.tick": ["Đánh dấu đã làm: {name}", "Mark as done: {name}"],
  "skin.weekDone": ["Đã làm trong tuần", "Done this week"],
  "skin.weekAm": ["Sáng", "Morning"],
  "skin.weekPm": ["Tối", "Night"],
  "skin.noRoutine": ["Chưa có bước nào. Thêm routine vào hồ sơ (xem docs/profile.md).", "No steps yet. Add a routine to your profile (see docs/profile.md)."],
  "vw.level": ["Trung bình", "Medium"],
  "set.data": ["Hồ sơ và dữ liệu", "Profile and data"],
  "set.dataHelp": ["Hồ sơ lưu trong trình duyệt này (localStorage), không gửi đi đâu. Xuất ra để sao lưu hoặc mang sang máy khác.", "Your profile stays in this browser (localStorage) and is never sent anywhere. Export it to back it up or move it to another device."],
  "set.export": ["Xuất hồ sơ (JSON)", "Export profile (JSON)"],
  "set.import": ["Nhập hồ sơ (JSON)", "Import profile (JSON)"],
  "set.reset": ["Về hồ sơ gốc", "Back to the built-in profile"],
  "set.resetAsk": ["Bỏ hồ sơ đã nhập và các chỉnh sửa, quay về hồ sơ gốc?", "Discard the imported profile and your edits and go back to the built-in profile?"],
  "set.exported": ["Đã xuất hồ sơ", "Profile exported"],
  "set.imported": ["Đã nhập hồ sơ", "Profile imported"],
  "set.importErr": ["Không đọc được tệp: {why}", "Could not read the file: {why}"],
  "set.resetDone": ["Đã về hồ sơ gốc", "Back to the built-in profile"],
  "prof.help": ["Sửa tên, màu và nơi bạn sống ngay trong app; dùng Cài đặt để nhập hoặc xuất cả hồ sơ.", "Edit your name, colours and location in the app; use Settings to import or export the whole profile."],
  "inv.addTitle": ["Thêm món vào Đồ đang có", "Add an item to your kit"],
  "inv.fType": ["Loại", "Type"],
  "inv.fName": ["Tên món", "Item name"],
  "inv.fColor": ["Màu", "Colour"],
  "act.saveItem": ["Lưu món", "Save item"],
  "toast.itemAdded": ["Đã thêm vào Đồ đang có", "Added to your kit"],
  "toast.copiedList": ["Đã chép danh sách", "Copied the list"],
  "cd.adaptSub": ["Theo quy tắc khuôn mặt trong hồ sơ. Chỉ về đường nét, không đổi màu.", "From the face rules in your profile. Shapes only; colours stay as they are."],
  "cd.noRules": ["Hồ sơ chưa có quy tắc khuôn mặt nên chưa có gợi ý chỉnh.", "Your profile has no face rules yet, so there are no shape hints."],
  "prof.faceLabel": ["Khuôn mặt mộc", "Bare face"],
  "j.nen.grey": ["Gần như xám, sẽ làm da xỉn.", "Almost grey; it will dull the skin."],
  "j.nen.pink": ["Ngả hồng, dễ làm mặt ửng hồng.", "Leans pink; it can make the face look flushed."],
  "j.nen.yellow": ["Vàng rõ, làm da ngả vàng.", "Clearly yellow; it turns the skin yellow."],
  "j.nen.notSkin": ["Màu không giống màu da.", "Not a skin colour."],
  "j.nen.good": ["Sắc be trung tính, khớp undertone.", "Neutral beige that matches the undertone."],
  "j.nen.warm2": ["Tông W/vàng: làm da ngả vàng, dễ ngả cam khi oxy hóa.", "Warm or yellow shade: turns skin yellow and can oxidise orange."],
  "j.nen.warm1": ["Tông W/vàng: làm da ngả vàng.", "Warm or yellow shade: turns skin yellow."],
  "j.nen.vivid": ["Màu quá rực, dễ ngả cam khi oxy hóa.", "Too vivid; it can oxidise orange."],
  "j.nen.satMore": ["Đậm sắc hơn da, dễ ngả cam.", "More saturated than skin; it can turn orange."],
  "j.nen.satLess": ["Nhạt sắc hơn da, lên mặt sẽ xỉn xám.", "Less saturated than skin; it will look dull and grey."],
  "j.nen.lighter2": ["Sáng hơn da quá nhiều, mặt sẽ bệch.", "Far lighter than skin; the face will look pale."],
  "j.nen.darker2": ["Tối hơn da quá nhiều, chỉ dùng tạo khối.", "Far deeper than skin; use it for contour only."],
  "j.nen.lighter1": ["Sáng hơn da khoảng 1 tông, hợp làm che quầng hơn.", "About one shade lighter than skin; better as an under-eye concealer."],
  "j.nen.darker1": ["Tối hơn da khoảng 1 tông, hợp khi da rám nắng.", "About one shade deeper than skin; fits when skin is tanned."],
  "j.nen.closeL": ["Độ sáng sát với da.", "Lightness is close to skin."],
  "j.che.mintOk": ["Xanh lá mint nhạt: color correct vùng đỏ. Chấm rất mỏng chỉ ở chỗ đỏ, phủ che khuyết điểm be trung tính lên.", "Pale mint: colour-corrects redness. Dab very thinly on the red area only, then cover with a neutral beige concealer."],
  "j.che.mintBad": ["Xanh lá quá đậm hoặc quá rực: lên da thành mảng xám. Chọn mint nhạt pastel.", "Green that is too deep or vivid turns into a grey patch on skin. Choose a pale pastel mint."],
  "j.che.grey": ["Xám, sẽ thành mảng tro dưới mắt.", "Grey; it will leave an ashy patch under the eyes."],
  "j.che.pink": ["Ngả hồng, có thể làm quầng tím và vùng đỏ rõ hơn.", "Leans pink; it can make purple shadows and red areas stand out."],
  "j.che.odd": ["Màu color correct này không hợp, hoặc chỉ dùng thật mỏng.", "This corrector colour does not suit; use it very thinly at most."],
  "j.che.yellow": ["Ngả vàng: trên vùng đỏ thành mảng vàng xỉn.", "Leans yellow; on red areas it becomes a dull yellow patch."],
  "j.che.peach": ["Tông đào, hợp color correct quầng thâm.", "Peach tone; suits colour-correcting dark circles."],
  "j.che.beige": ["Tông be trung tính, hợp undertone.", "Neutral beige; matches the undertone."],
  "j.che.dark2": ["Tối hơn da quá nhiều, lộ thành vệt tối.", "Far deeper than skin; it shows as a dark streak."],
  "j.che.dark1": ["Tối hơn da hơn 1 tông, quá tối cho che khuyết điểm.", "More than one shade deeper than skin; too deep for concealer."],
  "j.che.light2": ["Sáng quá nhiều, sẽ lộ vệt.", "Far too light; it will show as a streak."],
  "j.che.light1": ["Hơi sáng, chỉ dùng mỏng dưới mắt.", "Slightly light; use it thinly under the eyes."],
  "j.che.lightOk": ["Sáng hơn da một chút: dùng cho quầng mắt, không dùng chấm mụn.", "A little lighter than skin: for under-eye circles, not for spot cover."],
  "j.che.sameOk": ["Bằng hoặc tối hơn da tối đa 1 tông: đúng cho chấm mụn và thâm (không dùng dưới mắt nếu tối hơn da).", "Same as skin or at most one shade deeper: right for spots and marks (not under the eyes if deeper than skin)."],
  "j.ma.dull": ["Màu xỉn, ánh xám làm mặt mệt.", "Dull; the grey cast makes the face look tired."],
  "j.ma.good": ["Hồng be, hồng nâu, gạch hồng: hợp {season}.", "Beige rose, rose brown or brick rose: suits {season}."],
  "j.ma.peach": ["Đào và cam dễ lên hồng hoặc đỏ cam. Chọn màu hồng nâu.", "Peach and orange can turn pink or red-orange. Choose a rose brown."],
  "j.ma.fuchsia": ["Hồng fuchsia lạnh, bị nổi, lệch hẳn màu da.", "Cool fuchsia; it stands out and clashes with the skin."],
  "j.ma.purplish": ["Hồng ngả tím. Chọn màu nâu hơn.", "Leans purple-pink. Choose something browner."],
  "j.ma.yellowOrange": ["Cam vàng, giống bronzer hơn má hồng.", "Yellow-orange; reads as bronzer, not blush."],
  "j.ma.unnatural": ["Màu không tự nhiên trên má.", "Not a natural colour on the cheeks."],
  "j.ma.pale2": ["Quá nhạt so với độ đậm {season}.", "Too light for the depth of {season}."],
  "j.ma.pale1": ["Hơi nhạt so với độ đậm {season}, chọn màu đậm hơn.", "A little light for the depth of {season}; choose a deeper colour."],
  "j.ma.dark": ["Đậm, chỉ đánh thật mỏng.", "Deep; apply very lightly."],
  "j.ma.vivid": ["Quá rực. {season} hợp màu trầm, ít rực.", "Too vivid. {season} suits muted, less vivid colours."],
  "j.son.grey": ["Màu xám, làm môi nhợt.", "Grey; it makes lips look pale."],
  "j.son.good": ["Hồng nâu, gạch hồng, đỏ nâu, burgundy: hợp {season}.", "Rose brown, brick rose, brown red or burgundy: suits {season}."],
  "j.son.orange": ["Cam: dễ lên đỏ cam, dễ làm răng ngả vàng.", "Orange: can turn red-orange and make teeth look yellow."],
  "j.son.coolDeep": ["Hồng tím hoặc mận lạnh, làm da và răng ngả vàng.", "Cool purple-pink or plum; it makes skin and teeth look yellow."],
  "j.son.purplish": ["Ngả hồng tím. Chọn màu pha nâu hơn.", "Leans purple-pink. Choose a browner shade."],
  "j.son.yellowOrange": ["Cam vàng, làm răng trông vàng.", "Yellow-orange; it makes teeth look yellow."],
  "j.son.fashion": ["Màu thời trang, không phải màu son hằng ngày.", "A fashion shade, not an everyday lip colour."],
  "j.son.pale2": ["Quá nhạt so với độ đậm {season}, môi chìm và mặt nhợt.", "Too light for the depth of {season}; the lips vanish and the face looks pale."],
  "j.son.pale1": ["Hơi nhạt so với độ đậm {season}. Kẻ viền đậm hoặc chọn màu đậm hơn.", "A little light for the depth of {season}. Line with a deeper liner or choose a deeper colour."],
  "j.son.deepOk": ["Đủ đậm cho {season}.", "Deep enough for {season}."],
  "j.son.vivid": ["Quá rực. {season} hợp màu trầm, không neon.", "Too vivid. {season} suits muted colours, not neon."],
  "j.son.black": ["Gần đen, chỉ hợp tiệc hoặc phong cách riêng.", "Almost black; only for parties or a personal style."],
  "j.mat.coolGrey": ["Xám lạnh, làm bầu mắt thâm và mệt.", "Cool grey; it makes the lid look dark and tired."],
  "j.mat.silver": ["Trắng bạc, lộ nhũ và nếp da.", "Silver-white; it shows glitter and skin creases."],
  "j.mat.tooDark": ["Quá tối: chỉ dùng làm kẻ mắt. Phủ cả mí làm mắt nhỏ và sưng.", "Too dark: use it as liner only. Over the whole lid it makes eyes look small and puffy."],
  "j.mat.pinkPuffy": ["Hồng hoặc đỏ nhạt trên mí làm mắt trông sưng.", "Pale pink or red on the lid makes eyes look puffy."],
  "j.mat.tooLight": ["Quá nhạt: chỉ làm màu nền mắt. Làm màu chính thì mắt phẳng, mất chiều sâu.", "Too light: lid base only. As the main colour the eye looks flat and loses depth."],
  "j.mat.vivid": ["Quá rực so với bảng mắt kiểu Hàn.", "Too vivid for a Korean-style eye palette."],
  "j.mat.orange": ["Ngả cam hoặc vàng: dễ lên cam đỏ hoặc làm mí ngả vàng.", "Leans orange or yellow: can turn orange-red or make the lid look yellow."],
  "j.mat.olive": ["Ô liu hoặc khaki: chỉ dùng làm điểm nhấn.", "Olive or khaki: accent only."],
  "j.mat.cool": ["Màu lạnh, chỉ dùng làm kẻ mắt hoặc điểm nhấn.", "Cool colour: liner or accent only."],
  "j.mat.deepOk": ["Hợp, chỉ dùng sát mi và 1/3 đuôi mắt.", "Suits; keep it to the lash line and the outer third."],
  "j.mat.lightOk": ["Hợp làm màu nền mắt hoặc chuyển màu.", "Suits as a lid base or transition colour."],
  "j.mat.greyish": ["Hơi xám; chọn màu ấm hơn một chút.", "A little grey; choose something slightly warmer."],
  "j.mat.mainOk": ["Màu chính kiểu bảng Hàn: hồng nâu, cacao, trầm vừa.", "A main colour in the Korean-palette style: rose brown, cocoa, mid-muted."],
  "j.khoi.grey": ["Xám, nhìn như vết bẩn trên da ấm.", "Grey; it looks like a smudge on warm skin."],
  "j.khoi.notShadow": ["Màu không giống bóng đổ tự nhiên.", "Not like a natural shadow."],
  "j.khoi.orange": ["Quá cam/đỏ, giống bronzer cháy nắng.", "Too orange or red; it looks like a sunburnt bronzer."],
  "j.khoi.warm": ["Hơi ấm, dùng như bronzer hơn là tạo khối.", "A little warm; use it as bronzer rather than contour."],
  "j.khoi.good": ["Taupe nâu trung tính, giống bóng đổ thật.", "Neutral taupe brown, like a real shadow."],
  "j.khoi.notDeep": ["Không đủ đậm để tạo bóng.", "Not deep enough to make a shadow."],
  "j.khoi.veryDeep": ["Rất tối, dễ thành vệt; đánh cực mỏng.", "Very dark and streaky; apply extremely lightly."],
  "j.khoi.deepOk": ["Đậm hơn da vừa đủ.", "Just deeper than skin."],
  "j.hl.same": ["Bằng hoặc tối hơn da, sẽ không thấy hiệu ứng.", "Same as or deeper than skin; you will not see the effect."],
  "j.hl.weak": ["Chỉ hơi sáng hơn da, hiệu ứng yếu.", "Only slightly lighter than skin; a weak effect."],
  "j.hl.frost": ["Trắng frost, thành vệt xám trắng.", "White frost; it becomes a grey-white streak."],
  "j.hl.cool": ["Ánh lạnh (bạc, tím, xanh), bị nổi, lệch hẳn màu da.", "A cool cast (silver, purple, blue); it stands out and clashes with the skin."],
  "j.hl.gold": ["Vàng gold: làm da ngả vàng. Chọn champagne be hoặc soft gold.", "Gold: it turns skin yellow. Choose beige champagne or soft gold."],
  "j.hl.greyish": ["Hơi xám, ánh sáng lên da bị đục.", "A little grey; the glow turns cloudy on skin."],
  "j.hl.good8": ["Sáng hơn da rõ, sắc trung tính đến hơi hồng: hợp cả lì, glow và nhũ.", "Clearly lighter than skin, neutral to slightly pink: suits matte, glow and shimmer."],
  "j.hl.good": ["Sáng hơn da khoảng 1 tông, hợp highlight lì.", "About one shade lighter than skin; suits a matte highlight."],
  "j.may.tooLight": ["Quá sáng, mày sẽ mất nét.", "Too light; the brows will lose definition."],
  "j.may.black": ["Đen tuyền, làm mặt cứng.", "Pure black; it makes the face look harsh."],
  "j.may.ash": ["Xám tro, chân mày nhìn nhạt và cũ.", "Ash grey; brows look pale and dated."],
  "j.may.redOrange": ["Ngả đỏ hoặc cam, lệch màu tóc.", "Leans red or orange; it clashes with the hair."],
  "j.may.good": ["Nâu trung tính đến ấm, hợp tóc đen hoặc nâu.", "Neutral to warm brown; suits black or brown hair."],
  "j.may.odd": ["Màu hơi lạ cho chân mày.", "An unusual colour for brows."],
  "j.swapDefault": ["Đổi cho cùng tông với các màu còn lại trong bản của bạn.", "Swapped to sit with the other colours in your version."],
  "face.label": ["Minh họa khuôn mặt", "Face illustration"],
  "face.hl": ["bắt sáng {finish}", "{finish} highlight"],
  "face.lips": ["môi {style}", "{style} lips"]
};
